version: '3.7'
services:
  covid19_api_nginx:
    container_name: covid19_api_nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - "./../docs:/public_html"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:rw"
      - "./nginx/conf.d/:/etc/nginx/conf.d/:rw"

  covid19_data_parser:
    container_name: covid19_data_parser
    environment:
      CLONE_PATH: ${CLONE_PATH}
      LOG_PATH: ${LOG_PATH}
      FILE_WRITE_PATH: ${FILE_WRITE_PATH}
      SRC_DIR: ${SRC_DIR}
      ENV_DIR: ${ENV_DIR}
      # MYSQL
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      # POSTGRES
      POSTGRESS_HOST: ${POSTGRESS_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    build:
      context: ./../
      dockerfile: ./docker/data-parser/Dockerfile
      args:
        GIT_URL: "${GIT_URL}"
        CLONE_PATH: ${CLONE_PATH}
        LOG_DIR: ${LOG_DIR}
        LOG_PATH: ${LOG_PATH}
        FILE_WRITE_PATH: ${FILE_WRITE_PATH}
        SRC_DIR: ${SRC_DIR}
        ENV_DIR: ${ENV_DIR}
    depends_on:
      - covid19_mysql
      - covid19_postgress
    volumes:
    - "./../docs:/docs"


  covid19_mysql:
    image: mysql:5.7
    container_name: covid19_mysql
    command: mysqld --user=root
    volumes:
      - "./db/data/mysql:/var/lib/mysql"
      - ./db/structure/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql:ro
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  covid19_postgress:
    image: postgres:11.6
    container_name: covid19_postgress
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - ./db/data/postgers:/var/lib/postgresql/data
      - ./db/structure/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
    ports:
      - "6432:5432"






