version: '3.7'
services:
  covid19_data_parser:
    container_name: covid19_data_parser
    restart: unless-stopped
    env_file:
      - ./.env
    build:
      context: ./../
      dockerfile: ./docker/data-parser/Dockerfile
      args:
        LOG_DIR: ${LOG_DIR}
        LOG_PATH: ${LOG_PATH}
        FILE_WRITE_PATH: ${FILE_WRITE_PATH}
        SRC_DIR: ${SRC_DIR}
        ENV_DIR: ${ENV_DIR}
    depends_on:
      - covid19_mysql
      - covid19_postgress
    volumes:
      - "./../docs:/docs"


